version: '2.4'

services:
  mysql:
    container_name: mysql
    image: mysql:5
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:

volumes:
  db:
